In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
from sklearn import datasets, metrics

In [2]:
#load the dataset
heartdisease_df=pd.read_csv("heart.csv")
# Define the features and the outcome
X = heartdisease_df.iloc[:, :13]
y = heartdisease_df.iloc[:, 13]
# Replace missing values (marked by ?) with a 0
X = X.replace(to_replace='?', value=0)
# Binarize y so that 1 means heart disease diagnosis and 0 means no diagnosis
y = np.where(y > 0, 0, 1)
# Standarizing the features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)


1.Değişik eps ve min_samples değerleri deneyerek DBSCAN metodunu uygulayın. İki kümeli çözüm üretmenin pek kolay olmadığını göreceksiniz.


In [3]:
for i in range(1,100):
    dbscan_cluster = DBSCAN(eps=1, min_samples=i, metric='euclidean')
    clusters = dbscan_cluster.fit_predict(X_std)
    say=np.unique(clusters)
    if len(say)==2:
        print("aranan deger=",i,"olabilir")
        print(clusters)
        
        

aranan deger= 3 olabilir
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
aranan deger= 4 olabilir
[-1 -1 -1 -1 -1 -1 -1 -1 -1

Üstteki döngüyü iki parametre için de ayrı ayır çalıştırdım. Her biri için biri sabit diğrei birer artan 100 durum, ikisinin değerinin de aynı anda arttığı 100 durum olmak üzere toplam 300 farklı durum için de iki küme olan çıkmadı.Ama i=3 ve i=4 için bir kaç değer hariç hepsini -1 yani aykırı değer olarak görüyor. Eğer algoritmanın aykırı değer gördüklerini bir küme kabul edersek belki bir fikir verebilir.Bu kararı görselleştirerek daha iyi anlayabiliriz.

2.eps = 1, min_samples = 1, metric =" euclidean " şeklinde parametreleri ayarlayarak DBSCAN uygulayın. Ardından, min_samples değerini artırın. Artışın kümelerinin sayısı üzerindeki etkisi nedir?


In [4]:
dbscan_cluster = DBSCAN(eps=1, min_samples=1, metric='euclidean')

clusters = dbscan_cluster.fit_predict(X_std)

In [5]:
clusters

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,   6,  74,  75,
        76,  77,  67,  78,  79,  80,  81,  82,  83,  84,  15,  85,  86,
        87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 103, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,  73,
       137, 138, 139, 140, 141,  67, 142, 143, 144, 145, 146, 147, 148,
        67, 149, 150, 151, 152, 153, 154, 155, 155, 156, 157, 158, 159,
       160, 161, 162, 163, 164, 165, 166, 167, 168, 166, 169, 17

In [6]:
dbscan_cluster = DBSCAN(eps=1, min_samples=2, metric='euclidean')

clusters = dbscan_cluster.fit_predict(X_std)
clusters

array([-1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  2,  2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        3, -1, -1, -1, -1, -1,  4,  0, -1, -1, -1, -1,  3, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1,  4, -1, -1, -1, -1, -1,  3, -1, -1, -1, -1,
       -1, -1, -1,  3, -1, -1, -1, -1, -1, -1,  6,  6, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  7, -1, -1,  7, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [7]:
dbscan_cluster = DBSCAN(eps=1, min_samples=3, metric='euclidean')

clusters = dbscan_cluster.fit_predict(X_std)
clusters

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1,
       -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

min_samples parametresinin değerini artırdıkça küme sayımızız düştü.

3.eps = 1, min_samples = 1, metric =" euclidean " şeklinde parametreleri ayarlayarak DBSCAN uygulayın. Ardından, eps değerini artırın. Artışın kümelerinin sayısı üzerindeki etkisi nedir?

In [8]:
dbscan_cluster = DBSCAN(eps=1, min_samples=1, metric='euclidean')

clusters = dbscan_cluster.fit_predict(X_std)
clusters

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,   6,  74,  75,
        76,  77,  67,  78,  79,  80,  81,  82,  83,  84,  15,  85,  86,
        87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 103, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,  73,
       137, 138, 139, 140, 141,  67, 142, 143, 144, 145, 146, 147, 148,
        67, 149, 150, 151, 152, 153, 154, 155, 155, 156, 157, 158, 159,
       160, 161, 162, 163, 164, 165, 166, 167, 168, 166, 169, 17

In [9]:
dbscan_cluster = DBSCAN(eps=2, min_samples=1, metric='euclidean')

clusters = dbscan_cluster.fit_predict(X_std)
clusters

array([  0,   1,   2,   3,   4,   5,   2,   3,   6,   7,   3,   8,   3,
         9,  10,   8,  11,  12,   3,  13,  14,  15,   3,  16,  17,  18,
        19,   3,  20,  21,   8,  22,  23,  24,  25,  26,  27,  28,  18,
        29,  30,  23,  31,   2,  23,   3,  23,  23,  32,   2,  30,  33,
        34,   8,  30,   3,  23,  23,  35,   2,  36,   3,  37,  38,  39,
         8,  40,   2,   3,   8,  41,  42,  23,  43,   8,   2,  44,  45,
        46,  47,   3,  23,  11,  48,  49,  50,  51,  52,   8,  49,  53,
        45,  54,  55,   8,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         3,  65,  66,  67,   8,   2,  68,  69,  70,   3,   3,   8,  71,
        72,   8,  67,  73,  23,  74,  30,   8,   8,   3,  18,   2,  75,
        18,   8,   3,   3,   8,   8,  76,  39,  77,  78,  30,  79,   8,
        80,  81,  23,   8,  18,   3,   3,  82,  83,  84,  85,   8,  86,
         3,   3,  34,  87,  88,  11,   3,  54,  54,  89,  90,  91,  92,
        93,  94,  95,  33,  96,  90,  97,  98,  99,  97, 100,  7

In [10]:
dbscan_cluster = DBSCAN(eps=3, min_samples=1, metric='euclidean')

clusters = dbscan_cluster.fit_predict(X_std)
clusters

array([ 0,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,  1,  1,
        2,  1,  1,  1,  1,  1,  0,  1,  1,  0,  1,  3,  0,  1,  1,  1,  1,
        1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  3,  1,  1,  1,  0,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  0,  1,  1,  1,  1,  5,  1,
        6,  1,  0,  1,  1,  0,  1,  1,  3,  1,  1,  1,  7,  1,  0,  1,  8,
        1,  9,  1,  1,  0,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,
        1, 10,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       11,  0,  1,  1,  1,  1,  1,  1, 12,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 13,
        7,  1,  1,  1,  1,  1,  7,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, 14,  1,  7,  1, 15,  1,  1,  1, 16,
       17,  1,  1,  1,  1,  1,  1,  1,  1,  1,  7, 18,  1,  7,  1,  7, 19,
       20,  0, 21,  1,  1

Epsilon parametresinin değerini artırınca küme sayımız düştü.